name: Benchmark Image Loaders

on:
  push:

jobs:
  BenchSkiaSharp:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Run the benchmark
      working-directory: ./BenchSkiaSharp
      run: dotnet run -c Release

    - name: Print output
      run: cat ./BenchSkiaSharp/BenchmarkDotNet.Artifacts/results/BenchSkiaSharp.ImageLoader-report-github.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

  BenchSysDrawing:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # .NET Framework 4.8 is already pre-installed :)
    #  https://github.com/actions/runner-images/blob/16c64c111cb6372bf8949332d275b74c87d33075/images/windows/Windows2022-Readme.md#net-core-tools

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Get dependencies (dotnet restore)
      working-directory: ./BenchSysDrawing
      run: dotnet restore

    - name: Run the benchmark
      working-directory: ./BenchSysDrawing
      run: dotnet run -c Release

#    - name: Print output
#      run: cat ./BenchSysDrawing/BenchmarkDotNet.Artifacts/results/BenchSysDrawing.ImageLoader-report-github.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
